### ISSUE TITLE
No attribute with the name register_format exists?

### ISSUE THREAD

**Issue by gxfasd** [HomeOfVapourSynthEvolution/vsTAAmbk#21]
my script:

> core = vs.core
core.max_cache_size = 60000
ret= core.lsmas.LWLibavSource(r'C:\Users\Administrator\Desktop\1.avi')
ret=taa.TAAmbk(ret)
ret.set_output()
> 
run in vsediter:

> Failed to evaluate the script:
Python exception: No attribute with the name register_format exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2866, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 2867, in vapoursynth._vpy_evaluate
File "D:/video/VapourSynth64Portablevb/ok3.vpy", line 50, in 
ret=taa.TAAmbk(ret)
File "D:\video\VapourSynth64Portablevb\VapourSynth64\Scripts\vsTAAmbk.py", line 661, in TAAmbk
aa_clips = [aa_cycle(plane, aa_class, cycle, strength if yuv.index(plane) == 0 else 0, down8,
File "D:\video\VapourSynth64Portablevb\VapourSynth64\Scripts\vsTAAmbk.py", line 661, in 
aa_clips = [aa_cycle(plane, aa_class, cycle, strength if yuv.index(plane) == 0 else 0, down8,
File "D:\video\VapourSynth64Portablevb\VapourSynth64\Scripts\vsTAAmbk.py", line 601, in aa_cycle
aaed = aa_class(clip, *args, **kwargs).out()
File "D:\video\VapourSynth64Portablevb\VapourSynth64\Scripts\vsTAAmbk.py", line 210, in __init__
super(AAEedi2, self).__init__(clip, strength, down8)
File "D:\video\VapourSynth64Portablevb\VapourSynth64\Scripts\vsTAAmbk.py", line 30, in __init__
super(AAParent, self).__init__(clip)
File "D:\video\VapourSynth64Portablevb\VapourSynth64\Scripts\vsTAAmbk.py", line 25, in __init__
vs.GRAY10 = self.core.register_format(vs.GRAY, vs.INTEGER, 10, 0, 0).id
File "src\cython\vapoursynth.pyx", line 2434, in vapoursynth._CoreProxy.__getattr__
File "src\cython\vapoursynth.pyx", line 2308, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name register_format exists. Did you mistype a plugin namespace?

>

**Comment by kewenyu** [comment]
Try v0.8.2 if you are using Vapoursyth R55 or above.
